# -*- coding: utf-8 -*-
"""Práctica 4 ABD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qR4e8aTAsV_ImAe1wiTWHuDtrbhVWtlo

#Administración de Bases de Datos
# Práctica 4
## Estadísticas de lectura
###Alumna: Alma Yaneli Claudio Garcia

# Material
1. PostgreSQL
2. PG Admin 4
3. BD http://www.postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip

###El sistema operativo que se utilizara para la practica es el de Windows.

*   Descargamos la Base de Datos que esta comprimida en un archivo .zip del siguiente link:

    http://www.postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip

* Descomprimimos el archivo en una nueva carpeta, en mi caso en la carpeta bd.

* El archivo que se guardo en bd es un archivo con extencion .tar

### En la consola psql

* Creamos una nueva base de datos
"""

CREATE DATABASE dvdrental;

"""* Verificamos que se creo la base de datos dvdrental"""

\l

"""imagen 1

###En PG Admin 4

* Restauramos la base de datos que extrajimos en la carpeta bd

imagenes 2,3,4

### En la consola psql

* Ingresamos a la base de datos dvdrental
"""

\c dvdrental

"""imagen 5

* Visualisamos cuantas tablas tiene la base de datos dvdrental
"""

\dt

"""imagen 6

* Tomamos el tiempo que tarda en dar respuesta cada consulta
"""

\timing

"""imegen 7

* Contamos los registros que tiene la tabla actor
"""

select count(*) from actor;

"""imagen 8

* Mostramos todo lo que tiene la tabla actor
"""

select * from actor;

"""* Recopilamos las estadísticas sobre la tabla actor"""

ANALYSE actor;

"""imagen 9"""

SELECT * FROM pg_indexes WHERE tablename = 'actor';

"""imagen 10"""

SELECT pid , usename, application_name, client_addr, client_hostname, query, state from pg_stat_activity where datname='dvdrental';

"""imagen 11

* Plan de consulta consulta sobre una tabla actor
"""

EXPLAIN SELECT * FROM actor;

"""imagen 12"""

EXPLAIN ANALYZE SELECT * FROM actor;

"""imagen 13"""

EXPLAIN (ANALYZE, FORMAT YAML, BUFFERS) SELECT * FROM actor;

"""imagen 14"""